CREATE OR REPLACE FUNCTION getRoomsAvailable (startDateIN IN DATE, startTimeIN IN DATE, endDateIN IN DATE, endTimeIN IN TIME)
RETURN SYS_REFCURSOR
AS
  retCur SYS_REFCURSOR;
BEGIN
  OPEN retCur FOR SELECT RoomNo FROM Room WHERE 
